[package]
name = "phonecam-driver-linux"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
phonecam-protocol = { path = "../phonecam-protocol" }
v4l = "0.14"
nix = { version = "0.29", features = ["ioctl"] }

[dev-dependencies]
tempfile = "3.10"
