[package]
name = "phonecam-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
bytes = { version = "1.10", features = ["serde"] }
bincode = { version = "2.0", features = ["serde"] }

[dev-dependencies]
proptest = "1.6"
