[package]
name = "phonecam-desktop"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
phonecam-protocol = { path = "../phonecam-protocol" }
phonecam-transport = { path = "../phonecam-transport" }
phonecam-discovery = { path = "../phonecam-discovery" }
